### ISSUE TITLE
Progress isn't full

### ISSUE THREAD

**Issue by MuhRaihan001** [devbluen/Circle-Progress-Samp#1]
![sa-mp-014](https://github.com/devbluen/Circle-Progress-Samp/assets/87313996/729ddac8-aff7-4295-8491-2cb5b95618bc)
how do i fix the second progress isn't full
hunger[playerid] = CreatePlayerCircleProgress(playerid, 108.00, 379.00, 0x0388FCFF, 0xFFFFFFFF, 13.00, 0.30, 3.0);
thirst[playerid] = CreatePlayerCircleProgress(playerid, 136.00, 379.00, 0x0388FCFF, 0xFFFFFFFF, 13.00, 0.30, 3.0);

Have any suggestion?

**Comment by devbluen** [comment]
The polygons define the amount of resources that the samp will use to make the textdraw perfect, however you should never go beyond the limit, leave with fewer polygons so that the textdraw becomes more apparent and the balls that you will be able to create several circles.
